### ISSUE TITLE
File "app_process" was not created

### ISSUE THREAD

**Issue by avently** [abforce/xposed_app_process#2]
For some reason file app_process (/system/bin/app_process) is not created.
app_process32 & app_process64 are on their places but not app_process. 
This gives troubles with Magisk. It is trying to exec this file in a loop. Then system lags.

**Comment by abforce** [comment]
No idea. It has nothing to do with this module. During build process a symbolic link should be created whose name is `app_process` and points to `app_process32` or `app_process64`. Creating such symbolic link is done somewhere else not here.

**Comment by zaaraameera2014** [comment]
Sjkoklljb
